// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEvfLO7EzT9PVtW7diWoZkahJYESqkOiQ',
    appId: '1:1082601564353:web:c540bb13cdb2d22d09cc40',
    messagingSenderId: '1082601564353',
    projectId: 'chatapptest-b56a4',
    authDomain: 'chatapptest-b56a4.firebaseapp.com',
    storageBucket: 'chatapptest-b56a4.appspot.com',
    measurementId: 'G-GW46HB7NZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaSqLYUdUJO2v717wIJIzW8K16t1LswU',
    appId: '1:1082601564353:android:95436300ace494cb09cc40',
    messagingSenderId: '1082601564353',
    projectId: 'chatapptest-b56a4',
    storageBucket: 'chatapptest-b56a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrM9AFGJ5GAxaCUmRihKnN0gUvjj4i8rM',
    appId: '1:1082601564353:ios:19d96ccaaa2660c509cc40',
    messagingSenderId: '1082601564353',
    projectId: 'chatapptest-b56a4',
    storageBucket: 'chatapptest-b56a4.appspot.com',
    iosBundleId: 'com.example.dartpractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrM9AFGJ5GAxaCUmRihKnN0gUvjj4i8rM',
    appId: '1:1082601564353:ios:19d96ccaaa2660c509cc40',
    messagingSenderId: '1082601564353',
    projectId: 'chatapptest-b56a4',
    storageBucket: 'chatapptest-b56a4.appspot.com',
    iosBundleId: 'com.example.dartpractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEvfLO7EzT9PVtW7diWoZkahJYESqkOiQ',
    appId: '1:1082601564353:web:3d1ec4a79f5df9ba09cc40',
    messagingSenderId: '1082601564353',
    projectId: 'chatapptest-b56a4',
    authDomain: 'chatapptest-b56a4.firebaseapp.com',
    storageBucket: 'chatapptest-b56a4.appspot.com',
    measurementId: 'G-9J42WZV5X5',
  );

}